on:
  push:
    branches:
      - main
  pull_request:

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekker ut repoet
        uses: actions/checkout@v4

      - name: Installer Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Installer Pa11y CI
        run: npm install -g pa11y-ci

      - name: Run accessibility tests
        run: pa11y-ci
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
